17:19:12 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:19:12 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:19:14 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:19:17 - tele
[INFO] collect_msgs_from_channels:
 166 - ['', 'https://t.me/Rbinstagram']
17:19:18 - tele
[INFO] collect_msgs_from_channels:
 166 - ['', 'https://t.me/Rbinstagram', 'https://t.me/adbloggers']
17:19:19 - tele
[INFO] collect_msgs_from_channels:
 166 - ['', 'https://t.me/Rbinstagram', 'https://t.me/adbloggers', 'https://t.me/otzovik_blogger']
17:19:20 - tele
[INFO] collect_msgs_from_channels:
 166 - ['', 'https://t.me/Rbinstagram', 'https://t.me/adbloggers', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov']
17:19:21 - tele
[INFO] collect_msgs_from_channels:
 166 - ['', 'https://t.me/Rbinstagram', 'https://t.me/adbloggers', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov', 'https://t.me/fromBerek']
17:19:21 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:19:21 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
17:20:42 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:20:43 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:20:44 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:20:48 - tele
[INFO] collect_msgs_from_channels:
 168 - ['', 'https://t.me/otzovik_blogger']
17:20:49 - tele
[INFO] collect_msgs_from_channels:
 168 - ['', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov']
17:20:51 - tele
[INFO] collect_msgs_from_channels:
 168 - ['', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov', 'https://t.me/adbloggers']
17:20:52 - tele
[INFO] collect_msgs_from_channels:
 168 - ['', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov', 'https://t.me/adbloggers', 'https://t.me/fromBerek']
17:20:53 - tele
[INFO] collect_msgs_from_channels:
 168 - ['', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov', 'https://t.me/adbloggers', 'https://t.me/fromBerek', 'https://t.me/Rbinstagram']
17:20:53 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:20:53 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
17:24:56 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:24:56 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:24:58 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:25:00 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:25:00 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
17:25:34 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:25:35 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:25:35 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:25:38 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:25:38 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
17:25:54 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:25:54 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:25:55 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:26:00 - tele
[INFO] collect_msgs_from_channels:
 167 - ['', 'https://t.me/adbloggers']
17:26:00 - tele
[INFO] collect_msgs_from_channels:
 167 - ['', 'https://t.me/adbloggers', 'https://t.me/otzovik_blogger']
17:26:01 - tele
[INFO] collect_msgs_from_channels:
 167 - ['', 'https://t.me/adbloggers', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov']
17:26:02 - tele
[INFO] collect_msgs_from_channels:
 167 - ['', 'https://t.me/adbloggers', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov', 'https://t.me/Rbinstagram']
17:26:03 - tele
[INFO] collect_msgs_from_channels:
 167 - ['', 'https://t.me/adbloggers', 'https://t.me/otzovik_blogger', 'https://t.me/u_blogerov', 'https://t.me/Rbinstagram', 'https://t.me/fromBerek']
17:26:03 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:26:03 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
17:27:13 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:27:13 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:27:15 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:27:18 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:27:18 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
17:29:25 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:29:25 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:29:28 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:29:30 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:29:30 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
17:29:30 - tele
[ERROR] run:
 184 - Traceback (most recent call last):
  File "/home/unti1/MyWork/Orders/InstaTeleParser/tools/tele.py", line 182, in run
    self.collect_msgs_from_channels()
  File "/home/unti1/MyWork/Orders/InstaTeleParser/tools/tele.py", line 178, in collect_msgs_from_channels
    print(self.working_data())
          ^^^^^^^^^^^^^^^^^^^
TypeError: 'list' object is not callable

17:29:50 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:29:51 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:29:52 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:29:54 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:29:54 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
17:29:55 - tele
[ERROR] run:
 184 - Traceback (most recent call last):
  File "/home/unti1/MyWork/Orders/InstaTeleParser/tools/tele.py", line 182, in run
    self.collect_msgs_from_channels()
  File "/home/unti1/MyWork/Orders/InstaTeleParser/tools/tele.py", line 178, in collect_msgs_from_channels
    print(self.working_data())
          ^^^^^^^^^^^^^^^^^^^
TypeError: 'list' object is not callable

17:31:51 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
17:31:51 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
17:31:59 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
17:32:04 - mtprotosender
[INFO] _disconnect:
 317 - Disconnecting from 149.154.167.51:443/TcpFull...
17:32:04 - mtprotosender
[INFO] _disconnect:
 337 - Disconnection from 149.154.167.51:443/TcpFull complete!
16:39:21 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
16:39:21 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
16:39:22 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
16:39:57 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
16:39:57 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
16:39:57 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
16:40:56 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
16:40:56 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
16:40:56 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
19:50:24 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
19:50:24 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
19:50:25 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
20:04:35 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
20:04:35 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
20:04:36 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
20:05:17 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
20:05:17 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
20:05:26 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
20:05:26 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
20:05:27 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:25:57 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
02:25:57 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
02:25:58 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:33:10 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
02:33:10 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
02:33:11 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:33:58 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
02:33:58 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
02:33:59 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:34:33 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
02:34:33 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
02:34:34 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:49:30 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
02:49:30 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
02:49:30 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:49:41 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
02:49:41 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
02:49:42 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:57:14 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
02:57:15 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
02:57:32 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:57:35 - main
[ERROR] main_menu:
 166 - Traceback (most recent call last):
  File "/home/unti1/MyWork/Orders/InstaTeleParser/main.py", line 163, in main_menu
    self.general_start()
  File "/home/unti1/MyWork/Orders/InstaTeleParser/main.py", line 53, in general_start
    Instagram_Accounts = list(filter(lambda x: self.MainTreeProcesses[0].check_account_limit(x),Instagram_Accounts))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unti1/MyWork/Orders/InstaTeleParser/main.py", line 53, in <lambda>
    Instagram_Accounts = list(filter(lambda x: self.MainTreeProcesses[0].check_account_limit(x),Instagram_Accounts))
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unti1/MyWork/Orders/InstaTeleParser/tools/google.py", line 87, in check_account_limit
    elif count < int(config["Instagram"]["total_actions"]):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'

02:59:22 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
02:59:22 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
02:59:25 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
02:59:27 - main
[ERROR] main_menu:
 166 - Traceback (most recent call last):
  File "/home/unti1/MyWork/Orders/InstaTeleParser/main.py", line 163, in main_menu
    self.general_start()
  File "/home/unti1/MyWork/Orders/InstaTeleParser/main.py", line 57, in general_start
    self.MainTreeProcesses.append(InstPars(
                                  ^^^^^^^^^
  File "/home/unti1/MyWork/Orders/InstaTeleParser/tools/insta.py", line 12, in __init__
    self.browser_startUp(invisable = invisable)
  File "/home/unti1/MyWork/Orders/InstaTeleParser/tools/insta.py", line 62, in browser_startUp
    if USERPASSPROXY:
       ^^^^^^^^^^^^^
NameError: name 'USERPASSPROXY' is not defined

03:02:33 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
03:02:33 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
03:02:35 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
03:02:38 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:02:38 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:02:38 - logger
[INFO] log:
 11 - There is no [linux64] chromedriver for browser 110.0.5481 in cache
03:02:38 - logger
[INFO] log:
 11 - About to download new driver from https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_linux64.zip
03:02:41 - logger
[INFO] log:
 11 - Driver has been saved in cache [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481]
03:02:42 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:02:42 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:02:43 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:02:44 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:02:44 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:02:44 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:02:46 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:02:46 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:02:46 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:02:47 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:02:48 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:02:48 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:10:57 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
03:10:57 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
03:10:59 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
03:11:01 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:11:01 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:11:02 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:11:03 - main
[INFO] general_start:
 70 - Аккаунтов на все потоки не хватило
03:11:06 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:11:06 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:11:06 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:11:08 - main
[INFO] general_start:
 70 - Аккаунтов на все потоки не хватило
03:11:11 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:11:11 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:11:11 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:11:12 - main
[INFO] general_start:
 70 - Аккаунтов на все потоки не хватило
03:11:15 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:11:15 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:11:16 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:11:17 - main
[INFO] general_start:
 70 - Аккаунтов на все потоки не хватило
03:11:20 - logger
[INFO] log:
 11 - ====== WebDriver manager ======
03:11:20 - logger
[INFO] log:
 11 - Get LATEST chromedriver version for google-chrome 110.0.5481
03:11:20 - logger
[INFO] log:
 11 - Driver [/home/unti1/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
03:22:32 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
03:22:33 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
03:23:29 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
03:23:29 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
03:23:37 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
03:23:37 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
03:23:38 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
03:24:21 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
03:24:21 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
03:24:21 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
03:24:51 - mtprotosender
[INFO] _connect:
 226 - Connecting to 149.154.167.51:443/TcpFull...
03:24:51 - mtprotosender
[INFO] _connect:
 277 - Connection to 149.154.167.51:443/TcpFull complete!
03:24:51 - __init__
[INFO] autodetect:
 49 - file_cache is only supported with oauth2client<4.0.0
